language: node_js
sudo: required
install:
  - npm install -g yarn
script:
  - yarn install
  - yarn build
branches:
  only:
  - develop
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: develop
