language: node_js
sudo: required
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - "10"
install:
  - npm install -g yarn --cache-min 999999999
script:
  - yarn install
  - yarn test
  - yarn build
  - cp .travis.yml build
  - touch build/.nojekyll
  - echo gurunars.com > build/CNAME
branches:
  only:
    - develop
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  local-dir: build
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: develop
