# Generated by Django 2.2.2 on 2019-06-18 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('icon', models.ImageField(upload_to='')),
                ('owner', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
                ('owner', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Person')),
                ('type', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.LinkType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('color', models.CharField(max_length=10)),
                ('owner', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True)),
                ('artifacts', models.ManyToManyField(related_name='artifact_item', to='portfolio.Link')),
                ('location', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_item', to='portfolio.Link')),
                ('owner', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Person')),
                ('references', models.ManyToManyField(related_name='reference_item', to='portfolio.Link')),
                ('type', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.ItemType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('item', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Item')),
                ('owner', portfolio.models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
