name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure node
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: master
          FOLDER: build
          BUILD_SCRIPT: yarn install && yarn test && yarn build
          CNAME: gurunars.com
