name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure node
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Configure GIT
        run: |
          git config --global user.email "gurunars@gmail.com"
          git config --global user.name "Anton Berezin"

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv ./dist /tmp
          cd /tmp/dist

          git init
          git add .
          git commit -am init
          git push --force https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/gurunars/gurunars.github.io.git master
