name: CI

on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Configure node
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      - name: Install dependencies
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
      - name: Predeploy
        run: |
          touch build/.nojekyll
          echo gurunars.com > build/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACCESS_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build
